# Generated by Django 2.0.2 on 2019-04-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='logos')),
                ('signature', models.FileField(upload_to='signatures')),
                ('registration', models.CharField(max_length=100, verbose_name='IRS/CRA registration number')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(verbose_name='The date the gift was received')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='The amount received')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency abbreviation (e.g. USD/CAD)')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initials', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(upload_to='receipts')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_generator.Donation')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_generator.Donor'),
        ),
    ]
