# Generated by Django 2.1.8 on 2019-04-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('logo', models.FileField(upload_to='logos')),
                ('signature', models.FileField(upload_to='signatures')),
                ('registration', models.CharField(max_length=100, verbose_name='IRS/CRA registration number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address to receive copies of tax receipts.')),
                ('revenue_agency', models.CharField(max_length=3, verbose_name='Revenue agency, e.g. IRS or CRA')),
            ],
            options={
                'verbose_name_plural': 'Charities',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(verbose_name='The date the gift was received')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='The amount received')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency abbreviation (e.g. USD/CAD)')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_generator.Charity')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initials', models.CharField(blank=True, default='', max_length=10)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address to receive tax receipts.')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_pdf', models.FileField(upload_to='receipts')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_generator.Donation')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_generator.Donor'),
        ),
    ]
