# Generated by Django 2.0.2 on 2019-04-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipts',
            new_name='Receipt',
        ),
    ]
