# Generated by Django 2.1.8 on 2019-04-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
