# Generated by Django 2.0.2 on 2019-04-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='revenue_agency',
            field=models.CharField(max_length=3, verbose_name='Revenue agency, e.g. IRS or CRA'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='middle_initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
