# Generated by Django 2.1.8 on 2019-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='earmark_options',
            field=models.TextField(blank=True, verbose_name='Earmarking options (separated by a new line)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='earmark',
            field=models.CharField(blank=True, max_length=50, verbose_name='Earmarked for (can be blank)'),
        ),
    ]
