# Generated by Django 2.0.2 on 2019-04-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0002_auto_20190409_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name_plural': 'Charities'},
        ),
    ]
