# Generated by Django 2.0.2 on 2019-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0002_auto_20190418_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='middle_initials',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
