# Generated by Django 2.0.2 on 2019-04-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0003_auto_20190409_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email address to receive copies of tax receipts.'),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email address to receive tax receipts.'),
        ),
    ]
