# Generated by Django 2.0.2 on 2019-04-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0004_auto_20190418_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='address',
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.TextField(),
        ),
    ]
