# Generated by Django 2.0.2 on 2019-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0005_auto_20190418_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
