# Generated by Django 2.0.2 on 2019-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0006_auto_20190412_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email address to receive tax receipts.'),
        ),
    ]
